'use client';

import { CreditCard, Check, Info } from 'lucide-react';
import { Header } from '@/components/dashboard/Header';
import { OwnerOnlyGate } from '@/components/dashboard/OwnerOnlyGate';
import { Card, CardHeader, CardTitle, CardDescription } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { useToast } from '@/components/ui/Toast';
import { useStore } from '@/contexts/StoreContext';
import { PRICING_PLANS } from '@/lib/data/pricing-plans';
import { cn } from '@/lib/utils';

// The Free tier's plan name in the shared pricing copy — every store is on this plan today.
// There's no plan field on Store (nothing enforces it, nothing bills for it), so this is a
// display-only constant, not something read back from the backend.
const CURRENT_PLAN_NAME = 'STARTER';

export default function BillingPage() {
  return (
    <OwnerOnlyGate pageTitle="Billing" description="Billing and plan details are only visible to the store owner.">
      <BillingContent />
    </OwnerOnlyGate>
  );
}

function BillingContent() {
  const { store } = useStore();
  const { toast } = useToast();

  const handleUpgrade = (planName: string) => {
    toast(`Upgrading to ${planName} isn't available yet — billing isn't live. Reach out and we'll help you get set up when it is.`, 'info');
  };

  return (
    <>
      <Header title="Billing" subtitle="Manage your plan" />

      <main className="flex-1 overflow-y-auto p-4 md:p-6 space-y-6">

        {/* ── Not-yet-live notice ───────────────────────────────────────────── */}
        <div className="flex items-start gap-3 px-4 py-3.5 rounded-2xl border border-sky-200 bg-sky-50">
          <Info size={18} className="text-sky-600 shrink-0 mt-0.5" />
          <p className="text-sm text-sky-800">
            Billing is not yet active — all stores are currently on the Free tier at no cost.
            This page does not process payments; no invoices or charges are generated by ShopLink.
          </p>
        </div>

        {/* ── Current plan ──────────────────────────────────────────────────── */}
        <Card padding="md">
          <CardHeader>
            <div>
              <CardTitle>Current Plan</CardTitle>
              <CardDescription>{store.name}</CardDescription>
            </div>
            <Badge variant="success" dot>Free</Badge>
          </CardHeader>
          <div className="flex items-center gap-3 text-sm text-slate-600">
            <CreditCard size={16} className="text-slate-400 shrink-0" />
            No payment method on file — the Free plan doesn't require one.
          </div>
        </Card>

        {/* ── Plans ──────────────────────────────────────────────────────────── */}
        <div>
          <h2 className="text-base font-semibold text-slate-900 mb-1">Plans</h2>
          <p className="text-sm text-slate-500 mb-4">
            Pricing shown here matches the public pricing page. Upgrades aren't available yet.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {PRICING_PLANS.map(plan => {
              const isCurrent = plan.name === CURRENT_PLAN_NAME;
              return (
                <Card
                  key={plan.name}
                  padding="lg"
                  className={cn(isCurrent && 'ring-2 ring-primary-500')}
                >
                  <div className="flex items-center justify-between mb-2">
                    <h3 className="text-sm font-bold text-slate-900 tracking-wide">{plan.name}</h3>
                    {isCurrent && <Badge variant="primary">Current Plan</Badge>}
                    {plan.isPopular && !isCurrent && <Badge variant="purple">Popular</Badge>}
                  </div>

                  <div className="mb-1">
                    <span className="text-2xl font-bold text-slate-900">${plan.price}</span>
                    <span className="text-sm text-slate-500"> /{plan.period.replace('per ', '')}</span>
                  </div>
                  <p className="text-xs text-slate-500 mb-4">{plan.description}</p>

                  <ul className="space-y-2 mb-5">
                    {plan.features.map(feature => (
                      <li key={feature} className="flex items-start gap-2 text-sm text-slate-600">
                        <Check size={14} className="text-emerald-500 shrink-0 mt-0.5" />
                        {feature}
                      </li>
                    ))}
                  </ul>

                  {isCurrent ? (
                    <Button variant="secondary" fullWidth disabled>
                      Your Current Plan
                    </Button>
                  ) : (
                    <Button variant="outline" fullWidth onClick={() => handleUpgrade(plan.name)}>
                      Upgrade
                    </Button>
                  )}
                </Card>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}
